/* Stub for meshtastic/atak.pb.h
 * Generated by nanopb-0.4.9.1 — ATAK plugin not used in PURR OS.
 * module_config.pb.h includes this transitively via protobuf generation;
 * no ATAK types are actually referenced in the PURR OS build.
 */
#ifndef PB_MESHTASTIC_MESHTASTIC_ATAK_PB_H_INCLUDED
#define PB_MESHTASTIC_MESHTASTIC_ATAK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#endif
