// purr_device_glue.c — auto-generated by purrstrap for cyd
// Device: cyd  Chip: esp32
// Do not edit — regenerated on every purrstrap build.

#include "purr_kernel.h"
#include "purr_module.h"

#define CONFIG_DRV_DISPLAY_CS_PIN 15
#define CONFIG_DRV_DISPLAY_DC_PIN 2
#define CONFIG_DRV_DISPLAY_MOSI_PIN 13
#define CONFIG_DRV_DISPLAY_SCLK_PIN 14
#define CONFIG_DRV_DISPLAY_RST_PIN -1
#define CONFIG_DRV_DISPLAY_BL_PIN 21
#define CONFIG_DRV_TOUCH_SDA_PIN -1
#define CONFIG_DRV_TOUCH_SCL_PIN -1
#define CONFIG_DRV_TOUCH_INT_PIN 255
#define CONFIG_DRV_TOUCH_RST_PIN 255
#define CONFIG_GPS_TX_PIN 43
#define CONFIG_GPS_RX_PIN 44
#define CONFIG_LORA_MOSI_PIN -1
#define CONFIG_LORA_MISO_PIN -1
#define CONFIG_LORA_SCLK_PIN -1
#define CONFIG_LORA_CS_PIN -1
#define CONFIG_LORA_RST_PIN -1
#define CONFIG_LORA_IRQ_PIN -1

#define CONFIG_PURR_WIFI  1
#define CONFIG_PURR_BT    1
#define CONFIG_PURR_LORA  0

// Called from boot.c before purr_kernel_scan_modules().
void purr_device_init(void) {
    // Device: cyd
}

// Flash and SD module directories for this device.
const char *purr_flash_module_dir  = "/flash/modules";
const char *purr_flash_driver_dir  = "/flash/drivers";
const char *purr_flash_app_dir     = "/flash/apps";
const char *purr_sd_module_dir     = "/sdcard/modules";
const char *purr_sd_driver_dir     = "/sdcard/drivers";
const char *purr_sd_app_dir        = "/sdcard/apps";
