#!/usr/bin/env python3
"""
gen_sim_shell.py — PURR OS simulator shell generator.

Reads the real firmware shell source, substitutes PC-incompatible headers
with simulator compat headers, and writes a sim-ready .cpp to sim/generated/.

Usage (called by CMakeLists.txt):
    python gen_sim_shell.py --shell blackberry --out generated/shell_sim.cpp
"""

import argparse
import os
import sys

# ── Shell registry ────────────────────────────────────────────────────────────

SHELLS = {
    'blackberry': {
        'src':     '../CoreOS/system/kernel/modules/blackberry_ui.cpp',
        'defines': ['PURR_HAS_BLACKBERRY_UI=1', 'PURR_BBUI_TARGET_TOUCH=1',
                    'PURR_SIMULATOR=1'],
        'width':   320,
        'height':  240,
        'title':   'PURR OS — BlackberryUI (320x240)',
    },
    'explorer': {
        'src':     '../CoreOS/system/kernel/modules/explorer.cpp',
        'defines': ['PURR_HAS_EXPLORER=1', 'PURR_SIMULATOR=1'],
        'width':   320,
        'height':  240,
        'title':   'PURR OS — Explorer (320x240)',
    },
    'classicmac': {
        'src':     '../CoreOS/system/kernel/modules/classicmac.cpp',
        'defines': ['PURR_HAS_CLASSICMAC=1', 'PURR_SIMULATOR=1'],
        'width':   320,
        'height':  240,
        'title':   'PURR OS — ClassicMac (320x240)',
    },
    'classic': {
        'src':     None,   # uses existing mw_user.c — WIP/TBD
        'defines': [],
        'width':   320,
        'height':  240,
        'title':   'PURR OS — Classic Sim (MiniWin, TBD)',
    },
}

# ── Header substitutions applied to all shell sources ─────────────────────────

HEADER_SUBS = [
    # relative firmware includes → compat versions
    ('#include "../kitt.h"',           '#include "kitt_sim.h"'),
    ('#include "../purr_version.h"',   '#include "purr_version_sim.h"'),
    ('#include "display_ili9341.h"',   '#include "display_sim.h"'),
    ('#include "touch_cst816s.h"',     '#include "touch_sim.h"'),
    ('#include "partition_manager.h"', '#include "partition_sim.h"'),
    # system headers that don't exist on PC
    ('#include <Arduino.h>',           '#include "Arduino_sim.h"'),
    ('#include <freertos/FreeRTOS.h>', '#include "freertos/FreeRTOS_sim.h"'),
    ('#include <freertos/task.h>',     '#include "freertos/task_sim.h"'),
    ('#include <Preferences.h>',       '#include "Preferences_sim.h"'),
    ('#include <SPIFFS.h>',            '#include "SPIFFS_sim.h"'),
    ('#include <Wire.h>',              '#include "Wire_sim.h"'),
]

def generate(shell_name, out_path):
    if shell_name not in SHELLS:
        print(f"Unknown shell '{shell_name}'. Available: {', '.join(SHELLS.keys())}")
        sys.exit(1)

    cfg = SHELLS[shell_name]
    src_path = os.path.join(os.path.dirname(__file__), cfg['src']) if cfg['src'] else None

    os.makedirs(os.path.dirname(out_path) or '.', exist_ok=True)

    # Emit a CMake-includable info file alongside the source
    info_path = out_path.replace('.cpp', '.cmake')
    with open(info_path, 'w') as f:
        f.write(f'set(SIM_SHELL_WIDTH  {cfg["width"]})\n')
        f.write(f'set(SIM_SHELL_HEIGHT {cfg["height"]})\n')
        f.write(f'set(SIM_SHELL_TITLE  "{cfg["title"]}")\n')

    if src_path is None:
        # classic mode — nothing to generate
        with open(out_path, 'w') as f:
            f.write('// classic mode — uses mw_user.c directly\n')
        return

    with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
        src = f.read()

    # Apply header substitutions
    for old, new in HEADER_SUBS:
        src = src.replace(old, new)

    # Prepend define block so all PURR_* guards are satisfied
    defines = '\n'.join(f'#define {d.replace("=", " ")}' for d in cfg['defines'])
    header = f"""\
// AUTO-GENERATED by gen_sim_shell.py — DO NOT EDIT.
// Source: {cfg['src']}
// Shell:  {shell_name}  {cfg['width']}x{cfg['height']}

{defines}

// Compat includes must come before the shell source
#include "compat/sim_preamble.h"

"""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header + src)

    print(f"[sim] generated {out_path}  ({len(src)} bytes, {shell_name} {cfg['width']}x{cfg['height']})")

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--shell', required=True)
    ap.add_argument('--out',   required=True)
    args = ap.parse_args()
    generate(args.shell, args.out)
