/* Stub for meshtastic/atak.pb.h
 * Generated by nanopb-0.4.9.1 — ATAK plugin not used in PURR OS.
 * module_config.pb.h includes this transitively via protobuf generation.
 *
 * This stub was previously empty (per the archived comment: "no ATAK types
 * are actually referenced in the PURR OS build"), but that turned out to be
 * wrong — module_config.pb.h's meshtastic_ModuleConfig_TAKConfig struct (the
 * TAK team/role config nested inside ModuleConfig) references
 * meshtastic_Team/meshtastic_MemberRole directly, so the whole module_config
 * translation unit fails to compile without them, even though PURR OS never
 * reads or writes tak_config itself. This bug was latent in the archived
 * 0.11 code too — PURR_ENABLE_MESH defaulted off there, so this file was
 * never actually compiled until now. Values below are placeholders (not
 * necessarily matching real Meshtastic firmware's exact enum ordinals) —
 * good enough to satisfy the struct definition since nothing in this
 * codebase constructs a TAKConfig.
 */
#ifndef PB_MESHTASTIC_MESHTASTIC_ATAK_PB_H_INCLUDED
#define PB_MESHTASTIC_MESHTASTIC_ATAK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

typedef enum _meshtastic_Team {
    meshtastic_Team_Unspecifed_Color = 0,
    meshtastic_Team_Cyan             = 1,
    meshtastic_Team_Yellow           = 2,
    meshtastic_Team_Green            = 3,
    meshtastic_Team_Blue             = 4
} meshtastic_Team;

typedef enum _meshtastic_MemberRole {
    meshtastic_MemberRole_Unspecifed = 0,
    meshtastic_MemberRole_TeamMember = 1
} meshtastic_MemberRole;

#endif
