// purr_sdk.h — catstrap SDK v0.1.0
// Generated by: catstrap sdk install
// Compile with -DPURR_TIER_CLAW or -DPURR_TIER_PAWS.

#pragma once

#include <stdint.h>
#include <stdbool.h>

#if defined(PURR_TIER_CLAW)
#  include "purr_sdk_claw.h"
#elif defined(PURR_TIER_PAWS)
#  include "purr_sdk_paws.h"
#else
#  error "Define PURR_TIER_CLAW or PURR_TIER_PAWS before including purr_sdk.h"
#endif
