// blackpurr_icons.h — BlackPURR MDI icon declarations
// Auto-generated by convert_icons.py — do not edit
// Include this header in any BlackPURR source file.

#pragma once
#include "lvgl.h"

// ── Status bar icons (24×24) ─────────────────────────────────────────────────

extern const lv_img_dsc_t bp_icon_antenna_24;
extern const lv_img_dsc_t bp_icon_battery_alert_24;
extern const lv_img_dsc_t bp_icon_battery_charging_24;
extern const lv_img_dsc_t bp_icon_battery_full_24;
extern const lv_img_dsc_t bp_icon_battery_high_24;
extern const lv_img_dsc_t bp_icon_battery_low_24;
extern const lv_img_dsc_t bp_icon_battery_mid_24;
extern const lv_img_dsc_t bp_icon_bell_24;
extern const lv_img_dsc_t bp_icon_bell_off_24;
extern const lv_img_dsc_t bp_icon_bluetooth_24;
extern const lv_img_dsc_t bp_icon_gps_active_24;
extern const lv_img_dsc_t bp_icon_gps_off_24;
extern const lv_img_dsc_t bp_icon_gps_searching_24;
extern const lv_img_dsc_t bp_icon_radio_tower_24;
extern const lv_img_dsc_t bp_icon_sd_card_24;
extern const lv_img_dsc_t bp_icon_sd_off_24;
extern const lv_img_dsc_t bp_icon_signal_full_24;
extern const lv_img_dsc_t bp_icon_signal_off_24;
extern const lv_img_dsc_t bp_icon_volume_off_24;
extern const lv_img_dsc_t bp_icon_volume_on_24;
extern const lv_img_dsc_t bp_icon_wifi_24;
extern const lv_img_dsc_t bp_icon_wifi_off_24;

// ── App grid / drawer icons (48×48) ──────────────────────────────────────────

extern const lv_img_dsc_t bp_icon_about_48;
extern const lv_img_dsc_t bp_icon_add_app_48;
extern const lv_img_dsc_t bp_icon_all_apps_48;
extern const lv_img_dsc_t bp_icon_calculator_48;
extern const lv_img_dsc_t bp_icon_fileman_48;
extern const lv_img_dsc_t bp_icon_gps_48;
extern const lv_img_dsc_t bp_icon_magicmac_48;
extern const lv_img_dsc_t bp_icon_magidos_48;
extern const lv_img_dsc_t bp_icon_messages_48;
extern const lv_img_dsc_t bp_icon_radio_48;
extern const lv_img_dsc_t bp_icon_sd_card_48;
extern const lv_img_dsc_t bp_icon_settings_48;
extern const lv_img_dsc_t bp_icon_terminal_48;
extern const lv_img_dsc_t bp_icon_tools_48;

// ── Convenience macros ───────────────────────────────────────────────────────

#define BP_ICON_ABOUT_48   (&bp_icon_about_48)
#define BP_ICON_ADD_APP_48   (&bp_icon_add_app_48)
#define BP_ICON_ALL_APPS_48   (&bp_icon_all_apps_48)
#define BP_ICON_ANTENNA_24   (&bp_icon_antenna_24)
#define BP_ICON_BATTERY_ALERT_24   (&bp_icon_battery_alert_24)
#define BP_ICON_BATTERY_CHARGING_24   (&bp_icon_battery_charging_24)
#define BP_ICON_BATTERY_FULL_24   (&bp_icon_battery_full_24)
#define BP_ICON_BATTERY_HIGH_24   (&bp_icon_battery_high_24)
#define BP_ICON_BATTERY_LOW_24   (&bp_icon_battery_low_24)
#define BP_ICON_BATTERY_MID_24   (&bp_icon_battery_mid_24)
#define BP_ICON_BELL_24   (&bp_icon_bell_24)
#define BP_ICON_BELL_OFF_24   (&bp_icon_bell_off_24)
#define BP_ICON_BLUETOOTH_24   (&bp_icon_bluetooth_24)
#define BP_ICON_CALCULATOR_48   (&bp_icon_calculator_48)
#define BP_ICON_FILEMAN_48   (&bp_icon_fileman_48)
#define BP_ICON_GPS_48   (&bp_icon_gps_48)
#define BP_ICON_GPS_ACTIVE_24   (&bp_icon_gps_active_24)
#define BP_ICON_GPS_OFF_24   (&bp_icon_gps_off_24)
#define BP_ICON_GPS_SEARCHING_24   (&bp_icon_gps_searching_24)
#define BP_ICON_MAGICMAC_48   (&bp_icon_magicmac_48)
#define BP_ICON_MAGIDOS_48   (&bp_icon_magidos_48)
#define BP_ICON_MESSAGES_48   (&bp_icon_messages_48)
#define BP_ICON_RADIO_48   (&bp_icon_radio_48)
#define BP_ICON_RADIO_TOWER_24   (&bp_icon_radio_tower_24)
#define BP_ICON_SD_CARD_24   (&bp_icon_sd_card_24)
#define BP_ICON_SD_CARD_48   (&bp_icon_sd_card_48)
#define BP_ICON_SD_OFF_24   (&bp_icon_sd_off_24)
#define BP_ICON_SETTINGS_48   (&bp_icon_settings_48)
#define BP_ICON_SIGNAL_FULL_24   (&bp_icon_signal_full_24)
#define BP_ICON_SIGNAL_OFF_24   (&bp_icon_signal_off_24)
#define BP_ICON_TERMINAL_48   (&bp_icon_terminal_48)
#define BP_ICON_TOOLS_48   (&bp_icon_tools_48)
#define BP_ICON_VOLUME_OFF_24   (&bp_icon_volume_off_24)
#define BP_ICON_VOLUME_ON_24   (&bp_icon_volume_on_24)
#define BP_ICON_WIFI_24   (&bp_icon_wifi_24)
#define BP_ICON_WIFI_OFF_24   (&bp_icon_wifi_off_24)
